### ISSUE TITLE
My frok/continuation of Real Solar System

### ISSUE THREAD

**Issue by Minecraft633** [ow-mods/ow-mod-db#819]
### Mod uniqueName

xen.RealSolarSystem

### Mod name

Real Solar System Titan Edition

### GitHub repository URL

https://github.com/Minecraft633/outer-wilds-real-solar-system-titan-edition

### Tags

content

### Author display name

Titan2076 (Original by xen-42)

### DLC Required

None

### Alpha Mod

None

**Comment by xen-42** [comment]
Hey! Could you instead make a pull request from your fork of RSS to the original RSS? That way we can merge in the changes instead of fully replacing the mod on the database. While the mod has been inactive for a while there is still an in-development updated version being worked on, which you are welcome to contribute to. Cheers

**Comment by Minecraft633** [comment]
great
